# Generated by Django 4.0.3 on 2022-05-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
